scala:
  - 2.12.13
  - 2.13.6

language: scala
script: >
  sbt ++$TRAVIS_SCALA_VERSION check &&
  sbt ++$TRAVIS_SCALA_VERSION test

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier
