addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.5.1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.4.2")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"             % "3.9.7")
addSbtPlugin("com.github.sbt"     % "sbt-release"              % "1.0.15")
addSbtPlugin("com.codecommit"     % "sbt-github-actions"       % "0.11.0")
