addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.28")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.1")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.0.3")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"             % "2.3")
addSbtPlugin("com.github.gseitz"  % "sbt-release"              % "1.0.11")
